uav:
  J:
    J1: 3.4551e-5
    J2: 3.4551e-5
    J3: 5.0547e-5

  m: 0.036    #0.033
  d: 0.045
  ctf: 0.003699

controller:
  kx:       0.75
  kv:       0.11
  kr:       0.0013
  kOmega:   0.00065


# kx 0.12, kv 0.025, 0.0025, 0.0007

# first set the p values and see whether that'll reduce the error

#next: increase kr and komega. kx has enough room to increase other
# 3 gains. kv is almost in the ratio. so start with other two.


#with frame
#komega 0.0007 for kr = 0.0028 for kx = 0.245 kv = 0.066
#komega 00042 for kr = 0.00097 for kx = 0.27 kv = 0.1

# when kx increased there is room for all others to increase
# kr couldn't be increased above a certain value given the kv and
# kx is fixed. when kr reduces, kx could be increased a bit more.






#for ctf = 0.0036
#komega 00025 for kr = 0.00095 for kx = 0.27 kv = 0.1
#komega 00040 for kr = 00139 for kx = 0.22 kv = 0.09
#komega 00035 for kr = 00133 for kx = 0.22 kv = 0.07




trajectory:
  x0:
    x01: 0
    x02: 0
    x03: 0
  v0:
    v01: 0
    v02: 0
    v03: 0
  R0:
    R0_r1:
      r1_1: 1
      r1_2: 0
      r1_3: 0
    R0_r2:
      r2_1: 0
      r2_2: 1
      r2_3: 0
    R0_r3:
      r3_1: 0
      r3_2: 0
      r3_3: 1
  Omega0:
      Omega01: 0
      Omega02: 0
      Omega03: 0